"""Rest of the required models

Revision ID: 4c0cc57db6b3
Revises: 5853a188821a
Create Date: 2024-07-27 18:45:45.420825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0cc57db6b3'
down_revision = '5853a188821a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ac_last_message', sa.Boolean(), nullable=True),
    sa.Column('t_sensor_last_message', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature_sensor_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('status_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('LOST', 'CONNECTED', 'RUNNING', 'FINISHED', name='statusmessageenum'), nullable=False),
    sa.Column('sensor_message_id', sa.Integer(), nullable=True),
    sa.Column('aircon_command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircon_command_id'], ['aircon_command.id'], ),
    sa.ForeignKeyConstraint(['sensor_message_id'], ['temperature_sensor_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_message')
    op.drop_table('temperature_sensor_message')
    op.drop_table('last_messages')
    # ### end Alembic commands ###
