"""empty message

Revision ID: af785bdcef01
Revises: f53500fb1cb3
Create Date: 2024-08-03 02:18:37.849934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af785bdcef01'
down_revision = 'f53500fb1cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
