"""empty message

Revision ID: f53500fb1cb3
Revises: 4c0cc57db6b3
Create Date: 2024-08-03 02:11:01.191514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53500fb1cb3'
down_revision = '4c0cc57db6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('LOST', 'MATCH', 'MISMATCH', name='statusmessageenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('LOST', 'MATCH', 'MISMATCH', name='statusmessageenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
